### ISSUE TITLE
Convert Dots To Channel

### ISSUE THREAD

**Issue by jgarte** [iambumblehead/guix-home#1]
Hi!

WDYT of converting your dots to a channel so that any utility functions, packages, services, etc can be searched here:

https://toys.whereis.みんな/

See the info at the bottom of the page or here for convenience:

> If you'd like to join our channel webring send a patch to [~whereiseveryone/toys@lists.sr.ht](mailto:~whereiseveryone/toys@lists.sr.ht) adding your channel as an entry in [channels.scm](https://git.sr.ht/~whereiseveryone/toys/tree/master/item/channels.scm).

**Comment by iambumblehead** [comment]
Thank you, however, I can't effectively maintain or be responsible for these files at the moment. My current guix system isn't functional now due to https://debbugs.gnu.org/cgi/bugreport.cgi?bug=71951

Further, the update from wireplumber 0.4 to 0.5 left audio on the system in a broken state, which I can't attempt to fix until guix home reconfigure can be used.

the `yambar` and `libsixel` packages (found in this repo) were accepted upstream, so the only "special" guix package I have is a `bash_unit` package not found in this repo (submitted but not accepted upstream) https://debbugs.gnu.org/cgi/bugreport.cgi?bug=69975

I am busy with other things now and can't predict if I will use guix again the future.

**Comment by iambumblehead** [comment]
Yay, problem is resolved. Possibly will send a new patch for bash_unit and an un-related bug-fix for a different package that I've been using locally.

Thanks for facilitating some positive movements for me :)

**Comment by jgarte** [comment]
Glad I can help!

BTW, I added `feature-prolog` to RDE recently:

https://git.sr.ht/~abcdw/rde/commit/4eb9f2e7492dae60b16f7ac0715e5089d9add963

Give it a try if interested. I'd be happy to hear feedback.
